/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '5/24/20, 9:25 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-754.6.3.el6.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36' 
 * Generated on web client 'http://localhost:10080/SASStudio/38/main?locale=en_US&zone=GMT-06%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F38%2F=' 
 *
 */

options validvarname=any;
ods noproctitle;
ods graphics / imagemap=on;

/* Scatter plot matrix macro */
%macro scatterPlotMatrix(xVars=, title=, groupVar=);
	proc sgscatter data=WORK.IMPORT;
		matrix &xVars / %if(&groupVar ne %str()) %then
			%do;
				group=&groupVar legend=(sortorder=ascending) %end;
		diagonal=(histogram normal) ellipse=(type=predicted alpha=0.05);
		title &title;
	run;

	title;
%mend scatterPlotMatrix;

/* Regression scatter plot macro */
%macro regressionScatterplot(xVar=, yVar=, title=, groupVar=);
	proc sgscatter data=WORK.IMPORT;
		plot (&yVar)*(&xVar) / %if(&groupVar ne %str()) %then
			%do;
				group=&groupVar legend=(sortorder=ascending) %end;
		reg;
		title &title;
	run;

	title;
%mend regressionScatterplot;

/* Histogram (one-way or two-way) */
%macro DEHisto(data=, avar=, classVar=);
	%local i numAVars numCVars cVar cVar1 cVar2;
	%let numAVars=%Sysfunc(countw(%str(&avar), %str( ), %str(q)));
	%let numCVars=%Sysfunc(countw(%str(&classVar), %str( ), %str(q)));

	%if(&numAVars>0 & &numCVars>0) %then
		%do;

			%if(&numCVars=1) %then
				%do;
					%let cVar=%scan(%str(&classVar), 1, %str( ), %str(q));

					proc sql noprint;
						select count(distinct &cVar) into :nrows from &data;
					quit;

					/* One-way histogram */
					proc univariate data=&data noprint;
						var &avar;
						class &cVar;
						histogram &avar / nrows=&nrows
             normal(noprint);
					run;

				%end;
			%else
				%do;

					/* One-way histogram of each class variable */
                
					%do i=1 %to %eval(&numCVars);
						%let cVar=%scan(%str(&classVar), &i, %str( ), %str(q));

						proc sql noprint;
							select count(distinct &cVar) into :nrows from &data;
						quit;

						proc univariate data=&data noprint;
							var &avar;
							class &cVar;
							histogram &avar / nrows=&nrows
                 normal(noprint);
						run;

					%end;

					/* Two-way histogram */
                %let cVar1=%scan(%str(&classVar), 1, %str( ), 
						%str(q));
					%let cVar2=%scan(%str(&classVar), 2, %str( ), %str(q));

					proc sql noprint;
						select count(distinct &cVar1) into :nrows from &data;
					quit;

					proc sql noprint;
						select count(distinct &cVar2) into :ncols from &data;
					quit;

					proc univariate data=&data noprint;
						var &avar;
						class &cVar1 &cVar2;
						histogram &avar / nrows=&nrows ncols=&ncols
             normal(noprint);
					run;

				%end;
		%end;
%mend DEHisto;

%scatterPlotMatrix(xVars=Intensity_of_Binge Prevalence_of_Binge_Drinking, 
	title="Scatter plot matrix grouped by State", groupVar=State);
%scatterPlotMatrix(xVars=Intensity_of_Binge Prevalence_of_Binge_Drinking, 
	title="Scatter plot matrix grouped by Year", groupVar=Year);
%regressionScatterplot(xVar=Intensity_of_Binge, 
	yVar=Prevalence_of_Binge_Drinking, 
	title="Prevalence_of_Binge_Drinking vs Intensity_of_Binge grouped by State", 
	groupVar=State);
%regressionScatterplot(xVar=Intensity_of_Binge, 
	yVar=Prevalence_of_Binge_Drinking, 
	title="Prevalence_of_Binge_Drinking vs Intensity_of_Binge grouped by Year", 
	groupVar=Year);
%DEHisto(data=WORK.IMPORT, avar=Intensity_of_Binge 
	Prevalence_of_Binge_Drinking, classVar=State Year);

proc sort data=WORK.IMPORT out=WORK.TempSorted4877;
	by State;
run;

proc boxplot data=WORK.TempSorted4877;
	plot (Intensity_of_Binge Prevalence_of_Binge_Drinking)*State / 
		boxstyle=schematic;
run;

proc sort data=WORK.IMPORT out=WORK.TempSorted4877;
	by Year;
run;

proc boxplot data=WORK.TempSorted4877;
	plot (Intensity_of_Binge Prevalence_of_Binge_Drinking)*Year / 
		boxstyle=schematic;
run;

proc datasets library=WORK noprint;
	delete TempSorted4877;
	run;